### ISSUE TITLE
2017-05-11T17:42:24.73+0800 [APP/PROC/WEB/0] ERR Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.client.loadbalancer.LoadBalancerRequestTransformer

### ISSUE THREAD

**Issue by jackiilong** [spring-cloud-services-samples/greeting#12]

**Comment by lineshmehta5** [comment]
Update the pom.xml with 
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Camden.SR# 4</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

**Comment by royclarkson** [comment]
Please open a new issue if this remains a problem. Thanks.
