### ISSUE TITLE
specify the buildpack explicitly to speed up deployment on Diego based CF

### ISSUE THREAD

**Issue by asaikali** [spring-cloud-services-samples/greeting#5]
the deploy script should specify the build-pack explicitly to speed up deployment on Diego based CF.

**Comment by viniciusccarvalho** [comment]
It's not that simple, admins can change the name of the buildpack and that could break the deployment. We can't simply force a specific buildpack

**Comment by scottfrederick** [comment]
I agree with @viniciusccarvalho - you can easily modify the deploy script to specify a buildpack yourself, but the project shouldn't assume the name of the Java buildpack that will be installed on every target system.
